name: Test
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  bump-checksums:
    runs-on: macOS-12
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: melusina-org/gha-install-macports@v1
      id: install-macports
    - name: Bump checksum
      run: |
        git ls-files -- '*/Portfile' | xargs dirname | xargs port bump
        if ! git diff --exit-code HEAD -- '*/Portfile'; then
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '<github-actions[bot]@users.noreply.github.com>'
          git commit --message 'Bump checksum' -- '*/Portfile'
          git push
        fi
  test:
    needs: bump-checksums
    runs-on: macOS-12
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: melusina-org/gha-install-macports@v1
      id: install-macports
    - name: Configure MacPorts
      run: |
        echo 'revupgrade_mode report' | sudo tee -a /opt/local/etc/macports/macports.conf
        cat <<-EOF | sudo tee /opt/local/etc/macports/sources.conf
        file://${{ github.workspace }} [nosync]
        rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]
        EOF
    - name: Lint
      run: git ls-files -- '*/Portfile' | xargs dirname | xargs -I% -n1 port -D % lint --nitpick
    - name: Install
      id: install
      run: git ls-files -- '*/Portfile' | xargs dirname | sudo xargs -I% -n1 port -D % install 2>&1 | tee "$TMPDIR/install.log"
    - name: Show failure log
      if: failure() && steps.install.outcome == 'failure'
      run: grep 'Error:' "$TMPDIR/install.log" | grep -o ' /[^ ]*[.]log ' | xargs cat
