name: Test
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: macOS-12
    defaults:
      run:
        shell: bash
    env:
      MACOS_VERSION: 12
      MACPORTS_VERSION: v2.8.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache-macports-pkg
      with:
        path: MacPorts.pkg
        key: macOS-${{ env.MACOS_VERSION }}-MacPorts-${{ env.MACPORTS_VERSION }}
    - name: Install MacPorts package
      if: steps.cache-macports-pkg.outputs.cache-hit != 'true'
      run: |
        gh release download --repo macports/macports-base --pattern 'MacPorts-*-${{ env.MACOS_VERSION }}-*.pkg' ${{ env.MACPORTS_VERSION }}
        sudo installer -pkg MacPorts-*-${{ env.MACOS_VERSION }}-*.pkg -target /
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add MacPorts path
      run: echo '/opt/local/bin' >> "$GITHUB_PATH"
    - name: Update MacPorts
      run: sudo port -v selfupdate
    - name: Configure MacPorts
      run: |
        echo 'revupgrade_mode report' | sudo tee -a /opt/local/etc/macports/macports.conf
        cat <<-EOF | sudo tee /opt/local/etc/macports/sources.conf
        file://${{ github.workspace }}
        rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]
        EOF
    - name: Check PortIndex
      run: |
        portindex
        git diff --exit-code HEAD -- PortIndex PortIndex.quick
    - name: Lint
      run: cut -d ' ' -f 1 PortIndex.quick | xargs port lint --nitpick
    - name: Install
      id: install
      run: cut -d ' ' -f 1 PortIndex.quick | sudo xargs port install 2>&1 | tee "$TMPDIR/install.log"
    - name: Show failure log
      if: failure() && steps.install.outcome == 'failure'
      run: grep 'Error:' "$TMPDIR/install.log" | grep -o ' /[^ ]*[.]log ' | xargs cat
