name: Update
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Update Portfiles
      id: update-portfiles
      run: .github/bin/update-portfiles
    - uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update portfiles
        branch: update-portfiles
        delete-branch: true
        title: Update Portfiles
        body: ${{ steps.update-portfiles.outputs.message }}
        author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
